language: c
dist: trusty

addons:
  apt:
    packages:
      - libasound2:i386
      - libz1:i386
      - libbz2-1.0:i386
      - libssl1.0.0:i386
      - libfreetype6:i386

env:
  - VERSION=61
  - VERSION=70

install: 
  - wget -O - get.pharo.org/$VERSION+vm | bash
  - ./scripts/disable-deprecation-warning.sh 
  - ./scripts/install-packages.sh Mike mike

script:
  - ./pharo mike.image test --no-xterm --fail-on-failure "Mike-Tests"
